export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_ACTIVITIES_LOADING = 'SET_USER_ACTIVITIES_LOADING';
export const SET_USER_ACTIVITIES_RANGE = 'SET_USER_ACTIVITIES_RANGE';
export const SET_USER_ACTIVITIES_DATA = 'SET_USER_ACTIVITIES_DATA';
export const SET_STATS = 'SET_STATS';
export const ERASE_STATS = 'ERASE_STATS';
